version: '3.8'

services:
  app:
    image: php:8.2-fpm
    container_name: php
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
    networks:
      - app-network
    depends_on:
      - mysql
    environment:
      - VIRTUAL_HOST=qubecare.test,openemr.test
      - LETSENCRYPT_HOST=qubecare.test,openemr.test
      - LETSENCRYPT_EMAIL=your-email@example.com

  node:
    image: node:18
    container_name: node
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - app-network
    # command: npm start

  mysql:
    image: mysql:latest
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: laravel
      MYSQL_USER: laraveluser
      MYSQL_PASSWORD: laravelpassword
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - 8080:80
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
