import { defineThemeConfig } from '@core'
import { Skins } from '@core/enums'
import { breakpointsVuetifyV3 } from '@vueuse/core'
import { h } from 'vue'
import { VIcon } from 'vuetify/components/VIcon'

// ❗ Logo SVG must be imported with ?raw suffix
import logo from '@images/log_qube_new.png'
import { AppContentLayoutNav, ContentWidth, FooterType, NavbarType } from '@layouts/enums'

export const { themeConfig, layoutConfig } = defineThemeConfig({
  app: {
    title: '',
    logo: h('div', { innerHTML: `<img src="${logo}" alt="Logo" style="width:140px;">` }),
    //logo: h('div', { innerHTML: logo, style: 'line-height:0; color: rgb(var(--v-global-theme-primary))' }),
    contentWidth: ContentWidth.Fluid,
    contentLayoutNav: AppContentLayoutNav.Vertical,
    overlayNavFromBreakpoint: breakpointsVuetifyV3.lg - 1, // 1 for matching with vuetify breakpoint. Docs: https://next.vuetifyjs.com/en/features/display-and-platform/
    i18n: {
      enable: true,
      defaultLocale: 'en',
      langConfig: [
        { label: 'English', i18nLang: 'en', isRTL: false },
        // { label: 'Afrikaans', i18nLang: 'af', isRTL: false },
        // { label: 'Arabic (Algeria)', i18nLang: 'ar-dz', isRTL: true },
        // { label: 'Arabic (Kuwait)', i18nLang: 'ar-kw', isRTL: true },
        // { label: 'Arabic (Libya)', i18nLang: 'ar-ly', isRTL: true },
        // { label: 'Arabic (Morocco)', i18nLang: 'ar-ma', isRTL: true },
        // { label: 'Arabic (Saudi Arabia)', i18nLang: 'ar-sa', isRTL: true },
        // { label: 'Arabic (Tunisia)', i18nLang: 'ar-tn', isRTL: true },
        { label: 'Arabic', i18nLang: 'ar', isRTL: true },
        // { label: 'Azerbaijani', i18nLang: 'az', isRTL: false },
        // { label: 'Bulgarian', i18nLang: 'bg', isRTL: false },
        { label: 'Bengali', i18nLang: 'bn', isRTL: false },
        // { label: 'Bosnian', i18nLang: 'bs', isRTL: false },
        // { label: 'Catalan', i18nLang: 'ca', isRTL: false },
        // { label: 'Czech', i18nLang: 'cs', isRTL: false },
        // { label: 'Welsh', i18nLang: 'cy', isRTL: false },
        // { label: 'Danish', i18nLang: 'da', isRTL: false },
        // { label: 'German (Austria)', i18nLang: 'de-at', isRTL: false },
        { label: 'German', i18nLang: 'de', isRTL: false },
        // { label: 'Greek', i18nLang: 'el', isRTL: false },
        // { label: 'English (Australia)', i18nLang: 'en-au', isRTL: false },
        // { label: 'English (UK)', i18nLang: 'en-gb', isRTL: false },
        // { label: 'English (New Zealand)', i18nLang: 'en-nz', isRTL: false },
        // { label: 'Esperanto', i18nLang: 'eo', isRTL: false },
        { label: 'Spanish', i18nLang: 'es', isRTL: false },
        // { label: 'Estonian', i18nLang: 'et', isRTL: false },
        // { label: 'Basque', i18nLang: 'eu', isRTL: false },
        // { label: 'Persian', i18nLang: 'fa', isRTL: true },
        // { label: 'Finnish', i18nLang: 'fi', isRTL: false },
        { label: 'French', i18nLang: 'fr', isRTL: false },
        // { label: 'French (Switzerland)', i18nLang: 'fr-ch', isRTL: false },
        // { label: 'Galician', i18nLang: 'gl', isRTL: false },
        // { label: 'Hebrew', i18nLang: 'he', isRTL: true },
        { label: 'Hindi', i18nLang: 'hi', isRTL: false },
        // { label: 'Croatian', i18nLang: 'hr', isRTL: false },
        // { label: 'Hungarian', i18nLang: 'hu', isRTL: false },
        // { label: 'Armenian', i18nLang: 'hy-am', isRTL: false },
        // { label: 'Indonesian', i18nLang: 'id', isRTL: false },
        // { label: 'Icelandic', i18nLang: 'is', isRTL: false },
        // { label: 'Italian', i18nLang: 'it', isRTL: false },
        { label: 'Japanese', i18nLang: 'ja', isRTL: false },
        // { label: 'Georgian', i18nLang: 'ka', isRTL: false },
        // { label: 'Kazakh', i18nLang: 'kk', isRTL: false },
        // { label: 'Khmer', i18nLang: 'km', isRTL: false },
        { label: 'Korean', i18nLang: 'ko', isRTL: false },
        // { label: 'Kurdish', i18nLang: 'ku', isRTL: false },
        // { label: 'Luxembourgish', i18nLang: 'lb', isRTL: false },
        // { label: 'Lithuanian', i18nLang: 'lt', isRTL: false },
        // { label: 'Latvian', i18nLang: 'lv', isRTL: false },
        // { label: 'Macedonian', i18nLang: 'mk', isRTL: false },
        // { label: 'Malay', i18nLang: 'ms', isRTL: false },
        // { label: 'Norwegian Bokmål', i18nLang: 'nb', isRTL: false },
        // { label: 'Nepali', i18nLang: 'ne', isRTL: false },
        // { label: 'Dutch', i18nLang: 'nl', isRTL: false },
        // { label: 'Norwegian Nynorsk', i18nLang: 'nn', isRTL: false },
        // { label: 'Polish', i18nLang: 'pl', isRTL: false },
        // { label: 'Portuguese (Brazil)', i18nLang: 'pt-br', isRTL: false },
        { label: 'Portuguese', i18nLang: 'pt', isRTL: false },
        // { label: 'Romanian', i18nLang: 'ro', isRTL: false },
        { label: 'Russian', i18nLang: 'ru', isRTL: false },
        // { label: 'Sinhalese', i18nLang: 'si-lk', isRTL: false },
        // { label: 'Slovak', i18nLang: 'sk', isRTL: false },
        // { label: 'Slovenian', i18nLang: 'sl', isRTL: false },
        // { label: 'Samoan', i18nLang: 'sm', isRTL: false },
        // { label: 'Albanian', i18nLang: 'sq', isRTL: false },
        // { label: 'Serbian (Cyrillic)', i18nLang: 'sr-cyrl', isRTL: true },
        // { label: 'Serbian', i18nLang: 'sr', isRTL: false },
        // { label: 'Swedish', i18nLang: 'sv', isRTL: false },
        // { label: 'Tamil (India)', i18nLang: 'ta-in', isRTL: false },
        // { label: 'Thai', i18nLang: 'th', isRTL: false },
        // { label: 'Turkish', i18nLang: 'tr', isRTL: false },
        // { label: 'Uyghur', i18nLang: 'ug', isRTL: false },
        // { label: 'Ukrainian', i18nLang: 'uk', isRTL: false },
        // { label: 'Uzbek (Cyrillic)', i18nLang: 'uz-cy', isRTL: false },
        // { label: 'Uzbek', i18nLang: 'uz', isRTL: false },
        // { label: 'Vietnamese', i18nLang: 'vi', isRTL: false },
        // { label: 'Chinese (Simplified)', i18nLang: 'zh-cn', isRTL: false },
        // { label: 'Chinese (Traditional)', i18nLang: 'zh-tw', isRTL: false },
      ],
    },

    theme: 'light',
    skin: Skins.Default,
    iconRenderer: VIcon,
  },
  navbar: {
    type: NavbarType.Sticky,
    navbarBlur: true,
  },
  footer: { type: FooterType.Static },
  verticalNav: {
    isVerticalNavCollapsed: false,
    defaultNavItemIconProps: { icon: 'tabler-circle' },
    isVerticalNavSemiDark: false,
  },
  horizontalNav: {
    type: 'sticky',
    transition: 'slide-y-reverse-transition',
    popoverOffset: 6,
  },

  /*
    // ℹ️  In below Icons section, you can specify icon for each component. Also you can use other props of v-icon component like `color` and `size` for each icon.
    // Such as: chevronDown: { icon: 'tabler-chevron-down', color:'primary', size: '24' },
    */
  icons: {
    chevronDown: { icon: 'tabler-chevron-down' },
    chevronRight: { icon: 'tabler-chevron-right', size: 20 },
    close: { icon: 'tabler-x', size: 20 },
    verticalNavPinned: { icon: 'tabler-circle-dot', size: 20 },
    verticalNavUnPinned: { icon: 'tabler-circle', size: 20 },
    sectionTitlePlaceholder: { icon: 'tabler-minus' },
  },
})
